Order input changes
CrocSwap/ambient-ts-app pull request #2495
Opened 2023-06-16 16:58 UTC by Jadessu

### Describe your changes 
Refactor Swap, Range and Limit component on trade to match figma.
Live site:
<img width="388" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/83131501/ce6817b7-4dea-441d-bdb3-c172eae5dbb9">
<img width="380" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/83131501/016cc7dc-0e56-4d1e-a2e9-cb2b61e8c831">
<img width="385" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/83131501/2c149297-7ff7-48e4-aa4d-36dc08024f9d">
<img width="387" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/83131501/2322d126-1214-468e-b762-e5f855a28210">

Figma:
https://www.figma.com/file/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=4367-110918&t=6jCQWeMUcfqqUxJa-0
_Describe the purpose + content of these changes_
### Link the related issue
https://github.com/CrocSwap/ambient-ts-app/issues/2341
_Closes #2341 _

### Checklist before requesting a review
- [ ] Is this a PR meant for test purposes? If so, please open/change to a draft PR to indicate work in progress/test. 
- [x] I have performed a self-review of my code.
- [x] Did you request feedback from another team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

2023-06-20 21:40 UTC, surudhb commented
NOTE: part of the modal changes (mainly related to title centering) are done in https://github.com/CrocSwap/ambient-ts-app/pull/2503

2023-06-21 23:03 UTC, benwolski approved these changes

2023-06-22 03:13 UTC, miyuki-eto requested changes
there are a number of issues with this. noted below but also shown in the image and the link to the original markup in figma - 

1. inconsistent padding between items
2. border color to price impact warning is incorrect
3. price impact warning sides/width doesnt align
4. pool preset buttons have incorrect style
5. slider has the old visual bug of some additional bg element. this was previously fixed and is correct on the current live site. why is this back? 
6. apr value is incorrect colour - unbalanced mode doesnt need the ‘est apr’ text before the value either
7. swap module has extra padding to top. this is noticeable when you switch between order types
8. limit module wallet selector has different padding to other order types
9. the purple hover state was added to refresh button and settings button but not the share button

https://www.figma.com/file/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=6318%3A108900&t=SqjZHs8Aj0tQbDRg-1

![image](https://github.com/CrocSwap/ambient-ts-app/assets/82160202/3c06419a-0cd0-434c-837b-6943973a4411)

2023-06-23 03:49 UTC, miyuki-eto reviewed
this is looking much better. just a couple of small notes - 

1. can we update the colour of the text to the selected pool preset buttons? its currently dark1, but upon seeing it live on the site i think visibility would be increased of it was text1 instead
2. can we update the APR colours to be just a solid green (#41D18E, the standard green) this will just make it appear better i think and also match other green uses across the site

thank you!

2023-06-23 16:52 UTC, benwolski approved these changes

2023-06-23 16:54 UTC, merged