Support sci notation for exchange balance modals
CrocSwap/ambient-ts-app pull request #2580
Opened 2023-06-29 21:32 UTC by surudhb

### Describe your changes 
_Describe the purpose + content of these changes_

### Link the related issue
_Closes #0000_

### Checklist before requesting a review
- [ ] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [ ] I have performed a self-review of my code.
- [ ] Did I request feedback from a team member prior to merge? 
- [ ] Does my code following the style guide at `docs/CODING-STYLE.md`?

### Instructions for Reviewer
**Functionalities or workflows that should specifically be tested.**

1. Deposit/Withdraw/Transfer modals should now behave as expected with scientific input

2.

**Environmental conditions which may result in expected but differential behavior.**

1.

2.

### If relevant, list additional work to complete pre-merge (delete logging, code abstraction, etc)

2023-06-29 21:42 UTC, enwong10 approved these changes
LGTM - gonna hold off on merging until after https://github.com/CrocSwap/ambient-ts-app/pull/2527 gets merged

2023-07-03 17:21 UTC, benwolski requested changes
There appears to be inconsistent handling of input containing commas in the exchange balance module. Commas are getting immediately stripped from deposit quantity input, but they are allowed to remain in the Withdraw/Transfer sections. This is causing input like '2,000' in Withdraw/Transfer to get parsed as 2, rather than 2000.

2023-07-05 15:49 UTC, benwolski requested changes
seems the validity check is still getting stuck after an invalid input (e.g. -2)
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/a2eb3c33-8021-4998-89d4-788045c5dead)

2023-07-06 19:18 UTC, benwolski approved these changes

2023-07-06 19:18 UTC, merged