2680 enhancement recent transactions UI updates
CrocSwap/ambient-ts-app pull request #2760
Opened 2023-07-24 19:58 UTC by mishaHype

### Describe your changes 

1. remove the bottom white border to the tx cards - DONE
2. add rounding to card corners - DONE
3. make the pending tx loading spinner match the one used when updating price (thinner) - DONE
4. make the clear all button and hover state match the main submit swap buttons stylistically - DONE

### Link the related issue
Closes #2680

2023-07-24 21:08 UTC, benwolski requested changes
I think the waiting confirmation spinner is about 3x as fast now. was this intentional?

2023-07-25 02:38 UTC, mishaHype commented
> I think the waiting confirmation spinner is about 3x as fast now. was this intentional?

Its now using the same spinner class as the other areas of the website so should be all the same, i see what you mean by putting them next to each other. the spinner class also looks sleeker, this can be undone incase this is not wanted behaviour. Was trying to clean up some code

2023-07-28 23:54 UTC, surudhb approved these changes

2023-07-31 12:08 UTC, miyuki-eto commented
this looks good. i think the spinner being faster is ok and keeps consistency

2023-08-02 16:06 UTC, benwolski approved these changes

2023-08-02 16:06 UTC, merged