2778 enhancement use move cursor ie grabgrabbing instead of pointer cursor for sliders
CrocSwap/ambient-ts-app pull request #2787
Opened 2023-08-02 14:29 UTC by mishaHype

### Describe your changes 

- RangeSlider is now a component with its own styling in one spot.
- All users of the range slider now use the same component and the styling from it.
- FireFox now matches the slider in Chrome.
- IE has been depricated and is absolutley non accessible in 2023, removed any instances for it,
Microsoft states that all components of Chrome should work in Edge (Edge is based on chromium)

### Link the related issue
Closes #2778

2023-08-02 15:38 UTC, benwolski commented
@mishaHype, would it be possible to change the "grab" cursor to a "grabbing" cursor while the user is moving the sliders?

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/46ee603c-1c0c-49ad-9cab-5763582ef464)

2023-08-02 16:45 UTC, benwolski requested changes
@mishaHype, would it be possible to change the "grab" cursor to a "grabbing" cursor while the user is moving the sliders?

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/46ee603c-1c0c-49ad-9cab-5763582ef464)

2023-08-03 16:12 UTC, mishaHype commented
> @mishaHype, sorry if I was unclear. I think there should be two states to the cursor, one using the 'grab' cursor while the user is hovering over the slider, but not actively moving/grabbing the slider and then switching to the 'grabbing' cursor while the user is actively holding/moving the slider.

AH ok, that makes sence, ok will add that in

2023-08-03 20:43 UTC, benwolski approved these changes

2023-08-03 20:43 UTC, merged