Styled/trade
CrocSwap/ambient-ts-app pull request #2956
Opened 2023-09-01 22:57 UTC by enwong10

### Describe your changes 
Styled components for trade page 

TODO: missing secondary components (modals, tokenIcons, etc.)

### Link the related issue
_Closes #2702_

### Checklist before requesting a review
- [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

2023-09-04 18:03 UTC, benwolski requested changes
There appears to be a bug causing the details modal to open when certain modals are dismissed.

https://github.com/CrocSwap/ambient-ts-app/assets/570819/1c1067c1-28db-453b-8661-7e7260d2a2c3

2023-09-04 18:05 UTC, benwolski commented
These buttons are missing a pointer cursor on hover: 
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/961277ce-77b2-4822-aafb-a789a74e1df9)

2023-09-04 18:07 UTC, benwolski commented
Range price boundary placeholder values are appearing on one line instead of two: 
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/e272ff16-a6af-4a73-a64e-10f5af97b36a)

2023-09-04 18:09 UTC, benwolski commented
User cannot scroll to bottom of range module when extra info is expanded: 
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/a7bcacee-4c88-482c-9a55-0d2ac90e7ae9)

2023-09-04 18:14 UTC, benwolski commented
User can no longer invert range price boundaries within confirmation modal by clicking prices: 
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/c92ee539-813e-4eaf-8c5f-aea549da4e90)

2023-09-04 18:16 UTC, benwolski commented
Side/Type appearing on one row instead of two in column mode: 
![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/04079498-4370-45db-8c16-cce87baf4866)

2023-09-06 15:21 UTC, cadezacharias-hype reviewed
A couple touches from my review by inspection.

2023-09-06 15:21 UTC, cadezacharias-hype commented on src/App/App.css
Which actually seems like it was a mistake in the develop branch not to include.

2023-09-06 15:21 UTC, cadezacharias-hype commented on src/App/App.css
> -    color: var(--accent1) ;
![image](https://github.com/CrocSwap/ambient-ts-app/assets/96197989/95d456d9-489f-4c51-9ba1-9af1c3c46936)
Yours

![image](https://github.com/CrocSwap/ambient-ts-app/assets/96197989/8890e8f9-6d13-4a73-9fb8-9be5c57b20a1)


OG


Spacing on "Submit another transaction"

2023-09-06 17:41 UTC, enwong10 commented on src/App/App.css
>  }
what's the screensize for this? there are some sizes that hide the timestamp, make sure you're comparing apples to apples

2023-09-06 17:44 UTC, enwong10 commented on src/App/App.css
>  svg:hover {
because APR is right aligned and Status is left aligned - there used to be an extra padding on the header than I removed... @benwolski thoughts?

2023-09-12 19:52 UTC, benwolski approved these changes

2023-09-12 19:52 UTC, merged